accommodation/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve



urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('studentauth.url', namespace='studentauth')),
    path('', include('hostel.url', namespace='hostel')),
    path('',include('studentdashboard.url', namespace='studentdashboard'))


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG is False:  # Only add in production
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentauth/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
import string
from django.apps import apps

# Create your models here.

SCHOOL = (
    ('nile','Nile'),
    ('baze', 'Baze'),


)


GENDER = (
    ('male','Male'),
    ('female', 'Female'),


)

COUNTRY =(
    ('nigeria', 'NIGERIA'),
    ('ghana','GHANA'),
    ('southafrica', 'SOUTH AFRICA'),

)

IDENTITY_TYPE = (
    ('school id', 'SCHOOL ID'),
    ('acceptance letter', 'ACCEPTANCE LETTER'),
    ('school fees receipt', 'SCHOOL FEES RECEIPT')

)

HOSTEL = (
    ('white house','WHITE HOUSE'),
    ('jabi', 'JABI')

)


def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{instance.user.id, filename}.{ext}'
    return f"user_{instance.user.id}/{filename}"



class CustomUser(AbstractUser):
    name_regex = RegexValidator(regex=r'^[a-zA-Z\s]+$', message="Full name must contain only letters and spaces.")



    fullname = models.CharField(max_length=100, null=True, blank=True, validators=[name_regex])
    student_id = models.CharField(max_length=100,unique=True, null=True, blank=True)
    email = models.EmailField(max_length=200,null=True,blank=True,unique=True)
    phone = models.CharField(max_length=100,null=True,blank=True)
    username = models.CharField(max_length=100,null=True,blank=True,unique=True)
    gender = models.CharField(max_length=20, choices=GENDER)
    school = models.CharField(max_length=20, choices=SCHOOL,null=True,blank=True)
    level = models.CharField(max_length=20,null=True, blank=True)
    next_of_kin_fullname = models.CharField(max_length=100, null=True, blank=True)
    kin_phone = models.CharField(max_length=50,null=True, blank=True)
    kin_address = models.CharField(max_length=100, null=True, blank=True)



    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    groups = models.ManyToManyField(
        Group,
        related_name='custom_user_set',  # Custom related name to avoid clash
        blank=True,
        help_text=('The groups this user belongs to. A user will get all permissions granted to each of their groups.'),
        related_query_name='custom_user',
    )

    user_permissions = models.ManyToManyField(
        Permission,
        related_name='custom_user_permissions_set',  # Custom related name to avoid clash
        blank=True,
        help_text=('Specific permissions for this user.'),
        related_query_name='custom_user_permissions',
    )

    def clean(self):
        super().clean()
        if not self.email and not self.phone:
            raise ValidationError('Either email or phone must be provided.')
    

    def __str__(self):
        return self.email

class StudentProfile(models.Model):
    pid = ShortUUIDField(length=7,max_length=15,alphabet=string.ascii_letters + string.digits,primary_key=True)
    user = models.OneToOneField(CustomUser, related_name='profile', on_delete=models.CASCADE,unique=True)
    fullname = models.CharField(max_length=100,null=True,blank=True)
    student_id = models.CharField(max_length=100, unique=True, null=True, blank=True)
    department = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=200,null=True,blank=True,unique=True)
    phone = models.CharField(max_length=100,null=True,blank=True)
    image = models.FileField(upload_to=user_directory_path, default='default.jpg', null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER, null=True, blank=True)
    country = models.CharField(max_length=20, choices=COUNTRY, null=True, blank=True)
    city = models.CharField(max_length=200, null=True, blank=True)
    state = models.CharField(max_length=200, null=True, blank=True)
    postal_code = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    hostel = models.CharField(max_length=200,choices=HOSTEL, null=True,blank=True)
    identity_type = models.CharField(max_length=200, choices=IDENTITY_TYPE, null=True, blank=True)
    identity_image = models.FileField(upload_to=user_directory_path, null=True, blank=True)


    paid = models.BooleanField(default=False)

    date = models.DateField(auto_now_add=True)

    class meta:
        ordering = 'date'

    def get_booking_model(self):
        return apps.get_model('hostel.Booking')

    def get_hostel_model(self):
        return apps.get_model('hostel.Hostel')

    def __str__(self):

            return f'{self.fullname}'

studentdashboard/models.py
from django.db import models

# Create your models here.

studentdashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from hostel.models import Booking,Notification,Hostel,HostelType,Review
from studentauth.models import CustomUser, StudentProfile




def landing_page(request):
    hostels = Hostel.objects.filter(active=True)
    review = Review.objects.filter(active=True)


    context = {
        'hostels':hostels,
        'review':review

    }

    return render(request, 'studentdashboard/landing_page.html', context)




def dashboard(request):
    user = request.user
    booking = Booking.objects.filter(user=user, payment_status='Paid').last()  # Fix .objects
    hostels = Hostel.objects.filter(active=True,rating='top')  # Fix .objects and filter for all active hostels
    female_hostels = Hostel.objects.filter(active=True, gender='female')
    male_hostels = Hostel.objects.filter(active=True, gender='male')




    user = request.user
    school = getattr(user, 'school', None)


    if booking:  # Check if a booking exists
        notifications = Notification.objects.filter(user=user, seen=False,booking=booking)

        context = {
            'booking': booking,
            'notifications': notifications,
            'hostels': hostels
        }

        return render(request, 'studentdashboard/empty.html', context)

    else:
        context = {

            'hostels': hostels,
            'female_hostels':female_hostels,
            'male_hostels':male_hostels,


            'school':school

        }
        return render(request,'studentdashboard/empty.html', context)

def notification(request):
    notification = Notification.objects.filter(user=request.user, seen='False')

    context = {
        'notification': notification

    }

    return render(request, 'studentdashboard/notification.html', context)





@login_required
def bookings(request):
    booking = Booking.objects.filter(user=request.user).order_by('-date')

    context = {
        'booking': booking,


    }

    return render(request, 'studentdashboard/bookings.html', context)

@login_required
def booking_detail(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id,user=request.user)
    context = {
        'booking':booking

    }
    return render(request,'studentdashboard/bookingdetails.html',context)


@login_required
def personalInformation(request):
    profile = StudentProfile.objects.get(user=request.user)

    context = {
        'profile':profile

    }

    return render(request, 'studentdashboard/personalinformation.html', context)

templates/studentdashboard/accountSettings.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Sora:wght@100..800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/accountsettings.css' %}">

    <title>Mountainviewprovince.com</title>
</head>
<body>
    <div class="acc-sett-container font-sora">
        <div class="breadcrumb font-sora">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="prev-icon">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
            </svg>
            <p> Account Settings </p>
        </div>
        <div class="set-options">
            <a href="{% url 'studentauth:profile'  %}"  target="_blank">
                <div class="set-option">
                    <h3> Edit Profile</h3>
                    <p>Customize the personal information in your profile</p>
                </div>
            </a>
            <a href="{% url 'studentauth:change_password'  %}"  target="_blank">
                <div class="set-option">
                    <h3> Change Password </h3>
                    <p>Edit your password for easy authentication </p>
                </div>
            </a>
            <a href="" target="_blank">
                <div class="set-option">
                    <h3> Notification setting </h3>
                    <p>Customize the settings of your notification </p>
                </div>
            </a>
        </div>


    </div>
</body>
</html>

templates/studentdashboard/balance_invoice.html
{% load static %}
{% load humanize %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Sora:wght@100..800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/paymentsuccess.css">
    <link rel="stylesheet" href="{% static 'css/paymentsuccess.css' %}">
    <title>Mountainviewprovince.com</title>

    <style>

        *,
::before,
::after{
    box-sizing: border-box;
    font-family: "Sora", system-ui;
    font-optical-sizing: auto;
    font-style: normal;
}
body{
    background-color: #F1F1F1;
}
h1,h2,h3,h4,h5,h6,p{
    margin: 0;
    padding: 0;
}
.payment-successful-container{
    padding: 10px;
    height: auto;
}
.m-flex-col-b-radius{
    display: flex;
    align-items: center;
    justify-content: center;
    width: 30%;
    height: 15%;
    background-color: #EDC7AF;
    border-radius: 50%;
    margin: 20px auto;
}
.success-bar{
    text-align: center;
    margin-top: 5em;
    margin-bottom: 3.5em;
    margin-left: 0;
    margin-right: 0;
}
.success-bar p{
    font-weight: 600;
    font-size: 18px;
}
.success-title{
    margin: 2rem 0px;
}
.icon-holder{
    position: relative;
    width: 50px;
    height: 50px;
    background-image: url('../images/success-star-blank.png');
    background-size: contain;
    background-repeat: no-repeat;
}
.icon-holder::after {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 30%;
    height: 50%;
    background-image: url('../images/success-tick.png');
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center;
    transform: translate(-50%, -50%);
}
#transactionID,#date,#type-of-transac,#status,
#amount{
    display: flex;
    justify-content: space-between;
}
#payment-details h2{
    font-weight: 600;
    font-size: 16px;
    margin: 1rem 0px;
}
.payment-details-content{
    padding: 10px;
    border-radius: 5px;
    border: 1px solid rgba(161, 155, 155,0.5);
    background-color:#F0EBE8;
}
.payment-details-content div p:nth-of-type(1){
    font-weight: 400;
    font-size: 12px;
}
.payment-details-content div p:nth-of-type(2),a{
    font-weight: 600;
    font-size: 12px;
}
.payment-details-content div p{
    margin: 10px 0px;
}
.button-section{
    width: 100%;
    margin-top: 2rem ;
    margin-bottom: 1rem;
    margin-left: 0;
    margin-right: 0;
    text-align: center;
}
.m-btn{
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 5px;
    width: inherit;
    background-color: #863A0A;
    border: transparent;
    color: white;
    padding: 20px;
    border-radius: 5px;
    font-weight: 600;
    font-size: 14px;
}
.home_link{
    width: 100%;
    margin: 0rem 0;
    text-align: center;
}
a{
    text-decoration: none;
    color:#863A0A;
}

    </style>

</head>
<body>
    <div class="payment-successful-container">
        <div class="success-bar ">
            <div class="m-flex-col-b-radius">
                <div class="icon-holder">
                     <img src="{% static 'images/success-star-blank.png' %}" alt="">
                     <img src="{% static 'images/success-tick.png' %}" alt="" class="tick-icon">
                </div>
            </div>
            <p class="success-title"> Payment Succesful </p>
        </div>
        <section id="payment-details">
            <h2> Payment Details </h2>
            <div class="payment-details-content">
                <div id="transactionID">
                    <p>Booking ID: </p>
                    <p class="price">{{invoice.booking_id}}</p>
                </div>
                <div id="date">
                    <p>Date & Time: </p>
                    <p class="service-charge"> {{invoice.date}}</p>
                </div>
                <div id="type-of-transac">
                    <p>Type of Transaction: </p>
                    <p lass="booking"> Hostel booking </p>
                </div>
                <div id="status">
                    <p>Status: </p>
                    <p class="stat-bar"> {{invoice.payment_status}} </p>
                </div>

                 <div id="status">
                    <p>Room Type: </p>
                    <p class="stat-bar">{{invoice.hostel_type}} </p>
                </div>


                 <div id="amount">
                    <p>Rate Type: </p>
                    <p class="result"> {{invoice.rate_type}} </p>
                </div>

                <div id="amount">
                    <p>Amount: </p>
                    <p class="result"> ₦{{invoice.outstanding|intcomma}} </p>
                </div>

            </div>
        </section>

    </div>

</body>

</html>

templates/studentdashboard/bookingdetails.html
{% load static %}
{% load humanize %}
{% load number_to_word %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Sora:wght@100..800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bookingdetails.css' %}">
    <title>Mountainviewprovince.com</title>
</head>
<body>
    <div id="booking-detail-container " >
        <div class="breadcrumb">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="prev-icon">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
            </svg>
            <p> Booking Details</p>
        </div>
        <section id="selected-hostel">
            <div>
                <img class="selected-img" src="{% static 'images/booked-img.png' %}" alt="hostel's image" loading="lazy">
            </div>
            <div class="booked-details">
                <p class="hos-name">{{booking.hostel}}</p>
                <p class="booking">Booking ID: <span class="booking-id">{{booking.booking_id}}</span></p>
            </div>
        </section>
        <section id="room-details">
            <h2> Room Details </h2>
            <div class="room-details-content">
                <div id="room-no">
                    <p>Room number</p>
                    <p>Room {{booking.room.room_number}}</p>
                </div>
                <div id="n-bed">
                    <p>No of Bed</p>
                    <p>Three({{booking.room.capacity}})</p>
                </div>
                <div id="room-cat">
                    <p>Room Category</p>
                    <p>{{booking.hostel_type}}</p>
                </div>
                <div id="b-rate">
                    <p>Booking Rate</p>
                    <p>{{booking.rate_type}}</p>
                </div>
            </div>
        </section>
        <section id="payment-details">
            <h2> Payment Details </h2>
            <div class="payment-details-content">
                <div id="total-pay">
                    <p>Total Payment</p>
                    <p>&#8358 {{booking.rate_price|intcomma}}</p>
                </div>
                <div id="pay-date">
                    <p>Payment Date</p>
                    <p>{{booking.date}}</p>
                </div>
                <!--<div id="pay-method">
                    <p>Payment Method</p>
                    <p>#755,000</p>
                </div>-->
                <div id="pay-status">
                    <p>Pay Status</p>
                    <p>{{booking.payment_status}}</p>
                </div>
            </div>
        </section>
    </div>

</body>
</html>

templates/studentdashboard/bookings.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Sora:wght@100..800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/mybooking.css' %}">

    <title>Mountainviewprovince.com</title>
</head>
<body>
    <div class="booking-container">
        <div class="booking-header-section">
            <div class="booking-header-content">
                <h2 class="explore-title">My Bookings</h2>
                <p>Select from list of available hostels</p>
            </div>
        </div>
        {% for b in booking %}
        <a href="{% url 'studentdashboard:booking_detail' b.booking_id %}">
        <div class="booked-section">
            <div class="booking-capsule">
                <div class="image-bar left-pill">
                    <img
                    class="m-img"
                    src="{{b.hostel.image.url}}"
                    alt="hostel's image"
                    loading="lazy"
                    >
                </div>
                <div class="booking-content right-pill">
                    <p> BOOKING ID: <span class="booking-id">{{b.booking_id}}</span></p>
                    <p>{{b.hostel}}</p>
                    <p>{{b.hostel_type}}</p>
                    <!--<p>{{b.date}}</p>-->
                    <div id="status">
                        {% if b.payment_status == 'Paid' %}
                        <span class="success status-bar">
                            <img
                            src="{% static 'images/tick-circle.png' %}"
                            alt="success icon"
                            loading="lazy"
                            class="icons"
                            >
                            PAID

                        </span>
                        {% else %}
                             <span class="pending status-bar">
                            <img
                            src="{% static 'images/timer.png' %}"
                            alt="success icon"
                            loading="lazy"
                            class="icons"
                            >
                            {{b.payment_status}}
                        </span>
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
            </a>
        {%endfor%}

    </div>
</body>
</html>

templates/studentdashboard/dashboard.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Sora:wght@100..800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/home-2.css' %}">

    <title>Mountainviewprovince.com</title>
</head>
<body>
    <div class="home-container">
        <nav>
            <div class="mobile-nav">
                <span class="nav-ham">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="nav-icon">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>
                </span>
                <a href="{% url 'studentauth:profile'  %}"  target="_blank">

                <span class="prof-pic">
                    <img src="{{user.profile.image.url}}" alt="profile picture">
                </span>
                </a>
            </div>
        </nav>
        <section class="persona">
            <div class="persona-heading">
                <p> Hello <span>{{request.user.fullname}}</span></p>
                <h6>How are you doing today?</h6>
            </div>
        </section>
        <section class="current-booking">
            <h2>Your current booking</h2>
            <div class="flex top-banner">
                <div class="hostel-booked flex gap-1">
                    <img src="{{booking.hostel.image.url}}" alt="hostel booked" id="booked-img">
                    <span class="booked-box">
                        <p class="booked-text">{{booking.hostel.name}}</p>
                        <span class="flex location gap-1">
                            <svg width="14px" height="14px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">

                                <g id="SVGRepo_bgCarrier" stroke-width="0"/>

                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"/>

                                <g id="SVGRepo_iconCarrier"> <path fill-rule="evenodd" clip-rule="evenodd" d="M12 19C15.866 19 19 15.866 19 12C19 8.13401 15.866 5 12 5C8.13401 5 5 8.13401 5 12C5 15.866 8.13401 19 12 19ZM12 15C13.6569 15 15 13.6569 15 12C15 10.3431 13.6569 9 12 9C10.3431 9 9 10.3431 9 12C9 13.6569 10.3431 15 12 15Z" fill="#282727"/> <path d="M12 5V3" stroke="#282727" stroke-width="2" stroke-linecap="round"/> <path d="M19 12L21 12" stroke="#282727" stroke-width="2" stroke-linecap="round"/> <path d="M12 21L12 19" stroke="#282727" stroke-width="2" stroke-linecap="round"/> <path d="M3 12H5" stroke="#282727" stroke-width="2" stroke-linecap="round"/> </g>

                            </svg>
                            <p class="location-t"> View location</p>
                        </span>
                    </span>
                </div>
            </div>
            <div class="m-gray-box">
                <div class="p-x-2">
                    <div class="hostel-item">
                        <span class="flex gap-2 col-item">
                            <span class="r-item-icon left-icon">
                                <img src="{% static 'images/room-number.svg' %}" alt="key icon">
                            </span>
                            <div class="room-desk">
                                <p>Room Number</p>
                                <p class="fade"><span class="dynamic-text"> {{booking.room.room_number}}</p>
                            </div>

                        </span>
                    </div>
                    <div class="hostel-item">
                        <span class="flex gap-2 col-item">
                            <span class="r-item-icon left-icon">
                                <img src="{% static 'images/room-type.svg' %}" alt="room icon">
                            </span>
                            <div class="room-desk">
                                <p>Room Type</p>
                                <p class="dynamic-text">{{booking.hostel_type}}</p>
                            </div>

                        </span>
                    </div>
                    <div class="hostel-item">
                        <span class="flex gap-2 col-item">
                            <span class="r-item-icon left-icon">
                                <img src="{% static 'images/bed-type.svg' %}" alt="bed icon">
                            </span>
                            <div class="room-desk">
                                <p>Number of Bed</p>
                                <p class="dynamic-text">{{booking.room.capacity}} Bed</p>
                            </div>

                        </span>
                    </div>
                    <div class="hostel-item">
                        <span class="flex gap-2 col-item">
                            <span class="r-item-icon left-icon">
                                <img src="{% static 'images/clock.svg' %}" alt="clock icon">
                            </span>
                            <div class="room-desk">
                                <p>Date Paid</p>
                                <p class="dynamic-text"> {{booking.date}}</p>
                            </div>

                        </span>
                    </div>
                </div>
                <div id="request-section">
                    <div class="req-box gap-1">
                        <p> Submit Reviews/Ratings</p>
                        <span>
                            <img src="{% static 'images/arrow-right.svg' %}" alt="add icon">
                        </span>
                    </div>
                </div>
            </div>

        </section>
        <section class="m-request">
            <h2>Maintenance Request</h2>
            <div class="m-gray-box m-box">
                <div id="request-chambers" class="flex">
                    <div class="left-cut flex">
                        <span>
                            <img class="maint-img" src="{% static 'images/profile-icon.svg' %}" alt="maintenance image logo">
                        </span>
                        <span>
                            <p>Broken Faucet Repair</p>
                            <p>Ticket ID: <span>4356709</span></p>
                        </span>
                    </div>
                    <div class="status-holder">
                        <img class="status-icon" src="{% static 'images/pending.svg' %}" alt="pending icon">
                        <img class="status-icon not-active" src="{% static 'images/completed-icon.svg' %}" alt="completed icon">
                    </div>
                </div>
                <div id="request-chambers" class="flex">
                    <div class="left-cut flex">
                        <span>
                            <img class="maint-img" src="{% static 'images/profile-icon.svg' %}" alt="maintenance image logo">
                        </span>
                        <span>
                            <p>Broken Door Knob</p>
                            <p>Ticket ID: <span>43500709</span></p>
                        </span>
                    </div>
                    <div class="status-holder">
                        <img class="status-icon" src="{% static 'images/completed-icon.svg' %}" alt="pending icon">
                        <img class="status-icon not-active" src="" alt="completed icon">
                    </div>
                </div>
                <div id="request-section">
                    <div class="req-box gap-1">
                        <p> Make new request</p>
                        <span>
                            <img src="{% static 'images/add.svg' %}" alt="add icon">
                        </span>
                    </div>
                </div>

            </div>
        </section>
        <section class="m-request">
            <h2> Recent Notifications</h2>
            <div class="m-gray-box m-box">
                {% for n in notifications %}
                <div id="request-chambers" class="flex">
                    <div class="notification-area flex">
                        <span>
                            <img class="maint-img" src="{% static 'images/alert-icon.svg' %}" alt="maintenance image logo">
                        </span>

                        <span>
                            <p>Rent payment notification</p>
                            <p>Booking confirmed, Your booking id: {{n.booking.booking_id}}<span class="req-completed"><img class="status-icon" src="{% static 'images/completed-icon.svg' %}" alt="pending icon"></span></p>
                        </span>


                    </div>
                </div>
                {% endfor %}
                <div id="request-section">
                    <div class="not-box gap-1">
                        <p> View all notifications</p>
                        <span>
                            <img src="{% static 'images/arrow-right.svg' %}" alt="add icon">
                        </span>
                    </div>
                </div>

            </div>
                        <a href="/">logout</a>

        </section>
    </div>
</body>
</html>

templates/studentdashboard/empty.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/studentdashboard/password_changed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>